#spring.application.name=clickhousepipeline
#
#spring.datasource.url=jdbc:clickhouse://localhost:8123/logs?compress=0
#spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver
#spring.session.jdbc.initialize-schema=never
#spring.datasource.username=default
#spring.datasource.password=
#
#logging.level.com.yashraj.clickhousepipeline=INFO


spring.application.name=clickhousepipeline

# Use environment variables in Docker Compose
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.clickhouse.jdbc.ClickHouseDriver

# Connection pool settings (optional but nice)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# Logging level (your package)
logging.level.com.yashraj.clickhousepipeline=INFO
